services:
  app:
    build: .
    container_name: minha-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:6
    container_name: meu-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: meu-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
